@HostAddress = http://localhost:5182

GET {{HostAddress}}/books/
Accept: application/json

###

@BookId=F4B3E3B2-3B9A-4B5D-9B7B-2B0D7B3DCB6D
GET {{HostAddress}}/books/{{BookId}}
Accept: application/json

###

POST {{HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "Id": "B7FD313F-0FC6-4D94-9A91-2E742B7596C2",
  "Title": "The Silmarillion",
  "Author": "J.R.R. Tolkien",
  "Price": 20.99
}

###

GET {{HostAddress}}/books/B7FD313F-0FC6-4D94-9A91-2E742B7596C2
Accept: application/json

###

DELETE {{HostAddress}}/books/B7FD313F-0FC6-4D94-9A91-2E742B7596C2
Accept: application/json

###
