@HostAddress = https://localhost:7223

GET {{HostAddress}}/books/
Accept: application/json

###

@BookId=F4B3E3B2-3B9A-4B5D-9B7B-2B0D7B3DCB6D
GET {{HostAddress}}/books/{{BookId}}
Accept: application/json

###

POST {{HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "Id": "B7FD313F-0FC6-4D94-9A91-2E742B7596C2",
  "Title": "The Silmarillion",
  "Author": "J.R.R. Tolkien",
  "Price": 20.99
}

###

GET {{HostAddress}}/books/B7FD313F-0FC6-4D94-9A91-2E742B7596C2
Accept: application/json

###

DELETE {{HostAddress}}/books/B7FD313F-0FC6-4D94-9A91-2E742B7596C2
Accept: application/json

###
@NewPrice=19.99
PATCH {{HostAddress}}/books/B7FD313F-0FC6-4D94-9A91-2E742B7596C2/price
Accept: application/json
Content-Type: application/json

{
  "Price": {{NewPrice}}
}

###

POST {{HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email":"rickybobby@iwannagofast.com",
  "password":"$h4ke4ndb4kE"
} 

###

POST {{HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email":"rickybobby@iwannagofast.com",
  "password":"$h4ke4ndb4kE"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJyaWNreWJvYmJ5QGl3YW5uYWdvZmFzdC5jb20iLCJpYXQiOjE3MTY4MzMxNzksImV4cCI6MTcxNjgzNjc3OSwibmJmIjoxNzE2ODMzMTc5fQ.4eOojg7ayDQHSVrRkryQXJkRchyIVp7KWazIlCar4UI